!#68-Munkalap-szerkesztese
flowacademyhu/iota-munkalap pull request #100
Opened 2021-02-17 21:54 UTC by gyanyim

A backenden a munkalap szerkesztése (módosítása), történik ennek a kódnak a segítségével.

2021-02-17 22:07 UTC, borosr approved these changes

2021-02-18 05:55 UTC, akesztyus requested changes

2021-02-18 05:55 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +    @RolesAllowed({"admin", "user"})
Itt a keycloak client szintű rol-jait kell használni, ezek azok?

2021-02-18 05:55 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +        Worksheet updatedWorksheet = worksheetRepository.findById(id).orElseThrow(() -> new ValidationException("The id is null or not real: " + worksheet.getId()));
Inkább úgy fogalmazd meg a hibát, ahogyan a requestet küldő szempontjából érthető lesz: "No worksheet with the given id xyz"

2021-02-18 05:55 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +        updatedWorksheet.setPartnerId(worksheet.getPartnerId());
Ez a létrehozás mehetne private-ba, elég nagy, így nem clean.

2021-02-18 05:55 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +        if (worksheet.getTypeOfWork() == null) {
Ez már szerepelt a 102-ik sorban.

2021-02-18 06:43 UTC, ImreTheFifth approved these changes

2021-02-18 08:02 UTC, gyanyim commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +    @RolesAllowed({"admin", "user"})
Szia! Igen, ezek keycloak worksheetclient szintűek.

2021-02-18 10:06 UTC, borosr approved these changes

2021-02-18 15:05 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +    private void validateUpdatedWorksheet(Worksheet worksheet) throws ValidationException {
A két validációt nem lehetne összevonni?

2021-02-18 15:26 UTC, gyanyim commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +    private void validateUpdatedWorksheet(Worksheet worksheet) throws ValidationException {
Összevontam és töröltem a feleslegest.

2021-02-19 08:40 UTC, merged