!102-munkalapok-szurese-idopont-szerint
flowacademyhu/iota-munkalap pull request #107
Opened 2021-02-18 13:49 UTC by nomansnick

Sziasztok!

Felpusholtam az időpont szerinti szűrést.

Üdv,
Patrik

2021-02-18 14:00 UTC, VicziTomi approved these changes

2021-02-18 15:02 UTC, borosr requested changes

2021-02-18 15:02 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm:ss");
Erre nem lesz szükség, ha a contoller alapból parse-olja LocalDateTime-á a mezőket.

2021-02-19 08:43 UTC, borosr requested changes

2021-02-19 08:43 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +    @GetMapping("worksheets")
Határozd meg, hogy milyen szerepkörökkel elérhető.

2021-02-19 08:43 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +    public List<Worksheet> findByTimeInterval(@DateTimeFormat (pattern = "yyyy.MM.dd HH:mm:ss") @RequestParam (value = "maxTime") Optional<LocalDateTime> maxTime,
Ne legyen space az annotáció neve és a zárójel között.

2021-02-19 08:43 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +        if (maxTime.isEmpty()) {
Használd az orElse-t inkább és a service-ben, ne itt. Mindkét változóra.

2021-02-19 08:43 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +import java.time.format.DateTimeFormatter;
Ez az import nincs használva szerintem, nyomj majd egy organize imports-ot.

2021-02-19 13:53 UTC, borosr requested changes

2021-02-19 13:53 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +import java.util.stream.Collectors;
Mire használod a collectort?

2021-02-19 14:06 UTC, borosr approved these changes

2021-02-19 14:08 UTC, merged