!84-Munkalapok-listazasa
flowacademyhu/iota-munkalap pull request #109
Opened 2021-02-18 15:12 UTC by gyanyim

A Munkalapokat listázza ez a PR kód részlet.

2021-02-18 15:21 UTC, ImreTheFifth approved these changes

2021-02-18 16:20 UTC, VicziTomi approved these changes

2021-02-19 08:39 UTC, borosr requested changes

2021-02-19 08:39 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/WorksheetController.java
> +    public Worksheet createWorksheet(Authentication authentication, @RequestBody WorksheetDTO worksheetDTO) throws ValidationException {
Az `Authentication authentication`-re nem lesz szükség

2021-02-19 08:39 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/dto/WorksheetDTO.java
Itt ne legyen üres sor

2021-02-19 08:39 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/entity/Worksheet.java
> +
Itt ne legyen üres sor

2021-02-19 08:39 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/repository/UserRepository.java
> +    Page<User> findByEmailLikeIgnoreCaseOrFirstNameLikeIgnoreCaseOrLastNameLikeIgnoreCase(String emailPart, String firstNamePart, String lastNamePart, Pageable pageable);
Ezt már elvileg töröltük és criteria builderrel van megoldva. Nézd meg kérlek, hogy használjuk-e és, ha nem, töröld.

2021-02-19 08:39 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/WorksheetService.java
> +                .findAll(PageRequest.of(page.orElse(0),
Használd a `DEFAULT_PAGE` konstanst

2021-02-19 09:39 UTC, borosr approved these changes

2021-02-19 09:40 UTC, merged