!137-Bugfix-modify-sort-of-user-asc-to-desc
flowacademyhu/iota-munkalap pull request #138
Opened 2021-02-22 09:28 UTC by danielvarsas

Felhasználód listázásának sorrendje átírva.

2021-02-22 12:36 UTC, borosr requested changes

2021-02-22 12:36 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/UserService.java
> +                PageRequest.of(page.orElse(DEFAULT_PAGE), limit.orElse(pagingProperties.getDefaultLimit()), Sort.by(orderBy.orElse(DEFAULT_ORDERBY)).descending())
Írd át a tesztben is!

2021-02-22 13:02 UTC, ImreTheFifth requested changes
Linkelj issuet, pls

2021-02-23 08:41 UTC, danielvarsas commented on backend/src/main/java/hu/flowacademy/worksheet/service/UserService.java
> +                PageRequest.of(page.orElse(DEFAULT_PAGE), limit.orElse(pagingProperties.getDefaultLimit()), Sort.by(orderBy.orElse(DEFAULT_ORDERBY)).descending())
Átírva

2021-02-23 08:48 UTC, borosr approved these changes

2021-02-23 08:48 UTC, ImreTheFifth approved these changes

2021-02-23 08:48 UTC, merged