!16-munkalap-szerkesztese
flowacademyhu/iota-munkalap pull request #142
Opened 2021-02-22 11:26 UTC by MrCroo

Munkalapot lehet szerkeszteni hasonló módon mint a felhasználókat.
Nagy része ugyan az.

2021-02-22 11:28 UTC, MrCroo commented
Mikinek adtam munkát hogy a getById-t csinálja meg hozzá (mint a usereknél)

2021-02-22 12:59 UTC, ImreTheFifth approved these changes

2021-02-22 13:27 UTC, VicziTomi approved these changes

2021-02-22 14:51 UTC, 6uliver commented on frontend/src/employees/UpdateEmployee.js
> +  const [setSentSuccessfully] = useState(false)
Ez nagyon fura.

2021-02-22 14:54 UTC, 6uliver commented on frontend/src/worksheets/UpdateWorkSheet.js
> +  const [sent, setSent] = useState(false)
Ennél az egész résznél nagyon sok a duplikáció, elsőre még elfogadtam, de hogy már második helyen van szinte ugyanaz így egyedi hook-ért kiállt.

2021-02-22 14:56 UTC, 6uliver commented on frontend/src/worksheets/UpdateWorkSheetForm.js
> +  const typeOfWorkList = [
Ezeket a listákat én láttam már valahol... Lehet, hogy egy külön file-ba kellene kiszervezni őket és mindenhonnan azt használni? :)

2021-02-22 14:58 UTC, 6uliver commented on frontend/src/worksheets/UpdateWorkSheetForm.js
> +function UpdateWorkSheetForm({
Egyébként a létrehozó és a szerkesztő form között van különbség? Nagyrészt szerintem ugyanaz, a mezők ugyanazok, a validálás ugyanaz. Ha van némi különbség, akkor azt lehetne néhány prop-on keresztül állítgatni.

2021-02-22 15:51 UTC, MrCroo commented on frontend/src/worksheets/UpdateWorkSheetForm.js
> +function UpdateWorkSheetForm({
Ennél sokkal kevesebb adatot változtathatunk meg és a validálásból se ugyan azok kellenek

2021-02-23 12:07 UTC, 6uliver requested changes
A duplikáció miatt még ne menjen be, arról majd beszéljünk.

2021-02-23 14:05 UTC, 6uliver approved these changes

2021-02-23 14:05 UTC, merged