!-149worksheet-repository-update-irasa
flowacademyhu/iota-munkalap pull request #150
Opened 2021-02-22 15:53 UTC by nomansnick

2021-02-22 17:13 UTC, ImreTheFifth approved these changes

2021-02-22 18:15 UTC, borosr requested changes

2021-02-22 18:15 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/repository/WorksheetRepository.java
> +import java.util.Optional;
Ezt használod? Ha nem, töröld!

2021-02-23 09:19 UTC, gyanyim approved these changes

2021-02-23 11:15 UTC, borosr approved these changes

2021-02-23 11:15 UTC, merged