Fix/munkalap sorszama #170
flowacademyhu/iota-munkalap pull request #177
Opened 2021-02-24 18:07 UTC by nomansnick

2021-02-24 18:15 UTC, nomansnick commented
A teszt törik, ha megy az app, ha lelövöm lefut, arra hivatkozik, h:
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/patrik/GIT_FINAL_PROJEKT/iota-munkalap/backend/db/demo.mv.db [1.4.200/7]

Sztornó a pr jelenleg, hnap reggel javítom

2021-02-24 20:37 UTC, borosr commented
Megnézem a pipeline-t, esélyes, hogy csak futtatnunk kell a keycloak-ot hozzá.

2021-02-24 22:30 UTC, borosr commented
Ha mergeled a master, elvileg megoldódik a gond.

2021-02-25 09:25 UTC, borosr requested changes

2021-02-25 09:25 UTC, borosr commented on backend/src/test/java/hu/flowacademy/worksheet/controller/WorksheetControllerTest.java
> +    public void successfulCreationReturns201() {
Legyen test prefixe a teszteknek

2021-02-25 09:25 UTC, borosr commented on backend/src/test/java/hu/flowacademy/worksheet/controller/WorksheetControllerTest.java
> +                then()
Vizsgáld meg a response body-t, hogy tartalmazza a küldött adatokat illetve, hogy a sorszám ne legyen null.

2021-02-25 09:25 UTC, borosr commented on backend/src/test/java/hu/flowacademy/worksheet/helper/TestHelper.java
> +                .then()
vizsgáld meg a response status-t

2021-02-25 10:37 UTC, borosr approved these changes

2021-02-25 10:45 UTC, VicziTomi approved these changes

2021-02-25 10:46 UTC, merged