!131-Partner-letrehozasa
flowacademyhu/iota-munkalap pull request #187
Opened 2021-02-25 14:11 UTC by gyanyim

A PR segítségével létrehozható a Partner a rendszerben.

2021-02-25 14:34 UTC, VicziTomi requested changes
Ácsi! Nem a megfelelő issue van megjelölve, az a frontos-ra mutat.
Kérlek javítsd! (erre: https://github.com/flowacademyhu/iota-munkalap/issues/131)

2021-02-25 14:37 UTC, gyanyim commented
Bocsánat a hibáért, elnéztem! Javítottam!

2021-02-25 14:40 UTC, VicziTomi commented
ja és még egy pici: ez egy új feature, tehát a 'BUG' label is kerüljön le kérem.

2021-02-25 15:22 UTC, borosr approved these changes

2021-02-25 15:22 UTC, borosr commented
@VicziTomi részedről mergelhető?

2021-02-26 07:40 UTC, ImreTheFifth approved these changes

2021-02-26 07:41 UTC, merged

2021-02-26 07:42 UTC, ImreTheFifth commented
@VicziTomi , @borosr , A Tomi által kért formai módosítások kész lettek, utólagos engedelmetekkel zártam :D