!20-partnerek-listazasa
flowacademyhu/iota-munkalap pull request #192
Opened 2021-02-25 15:14 UTC by MrCroo

Megcsináltam a partnerek listázását. Kilistázza az adatokat amint lesz hozzá backend

2021-02-25 15:16 UTC, MrCroo commented
Annyi különbség (ami később változtatható könnyen), hogy láttam Mikinél az Addressnél van egy csomó adat, aminél nem tudom még mit kell megadni

2021-02-25 15:47 UTC, ImreTheFifth approved these changes

2021-02-25 17:31 UTC, 6uliver commented on frontend/src/Routing.js
> +          <TableListofPartners to="/partners" />
Itt maradjon a redirect szerintem, már van egy partners route, ami elvileg a TableListofPartners komponenst jeleníti meg. Máshol szerintem /partners-szel hivatkozunk rá, valamint ez a kezdőoldal, ami visz valahova, lehet ez változik, hogy mondjuk nem a partnerekre, hanem a munkalapokra szeretnénk navigálni indulásnál.

2021-02-25 17:32 UTC, 6uliver commented on frontend/src/api/PartnerAPI.js
> +function putPartner(id, credentials) {
Itt jobb lenne már nem a HTTP method szerint elnevezni, hanem hogy mit csinál:
put => updatePartner
post => createPartner

2021-02-25 17:34 UTC, 6uliver commented on frontend/src/partners/TableListofPartners.js
> +          <table className="table table-hover text-center">
A headerben 5 oszlop van, a partner esetén 4, töltés esetén 1. Ezt meg kellene oldani, lásd többi lista nézet.

2021-02-25 17:35 UTC, 6uliver requested changes
Amiket írtam apróságok légyszíves javítsd, egyébként szuper lett!

2021-02-26 10:11 UTC, VicziTomi approved these changes

2021-02-26 12:44 UTC, 6uliver commented on frontend/src/partners/Address.js
> +export default function partnerAddress({ partner }) {
Ez így egy komponens, ami ok, de konvenció szerint legyen a függvény neve akkor Address.

2021-02-26 12:45 UTC, 6uliver commented on frontend/src/partners/Address.js
> +      {partner.szamlazasiCimIranyitoszam +
Esetleg jobb lenne template literallal.

2021-02-26 12:45 UTC, 6uliver commented on frontend/src/partners/Address.js
> +        partner.szamlazasiCimTelepulesNev +
Érdemes lenne destructuring a return előtt vagy a paraméterlistában, hogy ne kelljen itt mindig leírni, hogy partner.

2021-02-26 12:46 UTC, 6uliver commented on frontend/src/partners/TableListofPartners.js
> +  const { partners } = usePartners()
Ha csak a partners jön vissza, akkor fölösleges objectbe rakni, elég vele visszatérni.

2021-02-26 12:46 UTC, 6uliver commented on frontend/src/partners/TableListofPartners.js
> +                    <td>{partner.adoszam}</td>
A headerben 5 oszlop van, itt csak 4, ez okozhat szétcsúszást. Kellene egy üres oszlop a módosítástnak.

2021-02-26 13:44 UTC, 6uliver approved these changes

2021-02-26 13:45 UTC, merged