!-208-munkalap-listazas-sorszam-szerint
flowacademyhu/iota-munkalap pull request #211
Opened 2021-02-27 07:32 UTC by nomansnick

2021-02-27 10:33 UTC, VicziTomi approved these changes

2021-02-28 22:03 UTC, borosr requested changes

2021-02-28 22:03 UTC, borosr commented on backend/src/test/java/hu/flowacademy/worksheet/service/WorksheetServiceTest.java
> +    private static final Pageable PAGEABLE = PageRequest.of(0, 1, Sort.by("createdAt").ascending());
Itt is id-t kellene megadni a createdAt helyett.

2021-03-01 20:04 UTC, borosr approved these changes

2021-03-01 20:05 UTC, merged