!203-partner-adoszam-kadoszam-lehessen-null
flowacademyhu/iota-munkalap pull request #219
Opened 2021-02-28 12:37 UTC by gyanyim

A partner létrehozásakor a magánszemély esetén nem adunk adószámot és k adószám típust az adatbázishoz. Illetve a @borosr kommentjei alapján átalakítottam a validációt.

2021-02-28 13:06 UTC, borosr requested changes

2021-02-28 13:06 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/PartnerService.java
> +    private boolean taxNumberLengthChecker(Partner partner) {
A taxNumberTypeChecker már vizsgálja a hosszt, nincs szükség erre.

2021-02-28 13:06 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/PartnerService.java
> +        boolean result = true;
Ne legyen erre külön változó, egyből vissza tudod adni a regex eredményét

2021-02-28 13:06 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/PartnerService.java
> +        if (partner.getBankszamlaszam().length() == 17 && partner.getBankszamlaszam().matches("^\\d{8}(-)\\d{8}$")) {
Nem kell a hossz-t vizsgálni, a regex megteszi helyetted és ne legyen result változó, hanem return-öld a két regex vizsgálatot vagy-gyal elválasztva, ugyan az lesz az eredménye.

2021-02-28 18:42 UTC, gyanyim commented on backend/src/main/java/hu/flowacademy/worksheet/service/PartnerService.java
> +        if (partner.getBankszamlaszam().length() == 17 && partner.getBankszamlaszam().matches("^\\d{8}(-)\\d{8}$")) {
Nem tudtam vagy-gyal elválasztani, ezért refactoráltam egy ternaryra!?

2021-02-28 22:01 UTC, borosr requested changes

2021-02-28 22:01 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/PartnerService.java
> +        return partner.getBankszamlaszam().length() == 17
Nem kell hozzá hosszt vizsgálni. Elég egy vagy művelete a két regex vizsgálat közé, mivel amennyiben az első minta nem illeszkedik, megpróbálja a másodikat és, ha az sem, akkor false-t ad vissza.

2021-02-28 22:24 UTC, borosr approved these changes

2021-03-01 07:07 UTC, VicziTomi approved these changes

2021-03-01 08:35 UTC, gyanyim commented
@VicziTomi Conflict feloldva, fogalmam sincs, hogy miért módosult az a frontend file!?

2021-03-01 11:58 UTC, VicziTomi commented
> @VicziTomi Conflict feloldva, fogalmam sincs, hogy miért módosult az a frontend file!?

Ez megoldódik? Kell hogy fent legyen a lock file? @gyanyim

2021-03-01 12:09 UTC, gyanyim commented
@SiposGergo -t kérdeztük és azt mondta, hogy fel szokták tölteni.

2021-03-01 20:01 UTC, borosr commented
@VicziTomi mergelném, áldásod adod rá?

2021-03-01 20:03 UTC, merged