!133-!134-partner-inaktiválása_aktivalasa
flowacademyhu/iota-munkalap pull request #225
Opened 2021-03-01 15:58 UTC by danielvarsas

A végpont csak egy ID-t vár. Megfordítja a partnet státuszának boolean értékét.

2021-03-01 20:00 UTC, borosr requested changes
Javítsd a hibás teszteket!

2021-03-01 20:05 UTC, borosr commented
Old fel a conflictot is!

2021-03-02 03:20 UTC, danielvarsas commented on backend/src/main/java/hu/flowacademy/worksheet/controller/PartnerController.java
> +    @PutMapping("/partners/{id}")
Done.

2021-03-02 08:33 UTC, borosr approved these changes

2021-03-02 08:44 UTC, VicziTomi approved these changes

2021-03-02 08:45 UTC, merged