!6_munkatár_inaktiválása
flowacademyhu/iota-munkalap pull request #49
Opened 2021-02-10 16:14 UTC by MrCroo

Csináltam egy gombot ami csak akkor jelenik meg ha Aktiv a felhasználó. A  DB-ből elkérem a usert és ellenőrizve átváltom a státuszát inaktivra(true-ról false-ra).

2021-02-10 16:22 UTC, ImreTheFifth requested changes
Pls legyen kebab-case a pr neve

2021-02-10 18:53 UTC, SiposGergo commented on frontend/src/UserAPI.js
>          .post(`/login`, values);
Nem konkrét hiba, de a values nem túl clean elnevezés, itt a loginnál lehetne pl.: credentials a paraméter neve.

2021-02-10 18:59 UTC, SiposGergo commented on frontend/src/employees/TableListOfEmployees.js
> +                        <Button
Ennek a gombnak nem kellene text prop-ot átadni, hogy legyen felirata?

2021-02-10 19:01 UTC, SiposGergo commented on frontend/src/employees/TableListOfEmployees.js
> +                      Active {
Az Active után nyitott kapcsos zárójel </td> előtt zárt kapcsos zárójelpár felesleges igazából

2021-02-10 19:09 UTC, MrCroo commented on frontend/src/UserAPI.js
>          .post(`/login`, values);
Igen, mondjuk ez a masterről került hozzám, de javitom majd :)

2021-02-10 19:13 UTC, MrCroo commented on frontend/src/UserAPI.js
>          .post(`/login`, values);
A masterből örököltem, de fixelem akkor :)

2021-02-10 19:33 UTC, MrCroo commented on frontend/src/employees/TableListOfEmployees.js
> +                        <Button
A Button-nek? Annak nem kell szerintem felirat. Jelenleg csak egy X

2021-02-10 19:53 UTC, SiposGergo commented on frontend/src/employees/TableListOfEmployees.js
> +                        <Button
Ha a PM szerint sem kell rá felirat, akkor részemről rendben :) @VicziTomi @ImreTheFifth

2021-02-10 20:04 UTC, MrCroo commented on frontend/src/employees/TableListOfEmployees.js
> +                        <Button
"a már aktivált munkatársak sorában legyen egy inaktiválás ikon" - Nekem ebből az jött le, de @VicziTomi megmondja :)

2021-02-11 07:03 UTC, VicziTomi commented on frontend/src/employees/TableListOfEmployees.js
> +                        <Button
Tegyük kérem egyértelművé a végfelhasználó számára, így megérdemel ez a gomb egy 'Inaktiválás' feliratot! Köszi! :)

2021-02-11 07:04 UTC, VicziTomi approved these changes
Részemről rendben!

2021-02-11 08:50 UTC, ImreTheFifth approved these changes

2021-02-11 11:57 UTC, 6uliver commented on frontend/src/Button.js
> +    aria-label={arialLabel}
Lehet olyat, hogy minden props-ot továbbítasz, paraméterlistában például: {text, ...props} és akkor lesz külön text változód valamint a maradék props, amit tovább lehet dobni a button-nek így: <button {...props}>

2021-02-11 12:51 UTC, MrCroo commented on frontend/src/employees/TableListOfEmployees.js
> +                        onClick={() => putUserInactive(user.id)}
Ezzel a részével esetleg később foglalkoznék ha lesz most backend

2021-02-11 13:10 UTC, 6uliver commented on frontend/src/employees/TableListOfEmployees.js
> +                        onClick={() => putUserInactive(user.id)}
@MrCroo rendben, akkor mergelem, amint feloldottátok a conflictot.

2021-02-11 15:21 UTC, MrCroo commented on frontend/src/employees/TableListOfEmployees.js
> +                        onClick={() => putUserInactive(user.id)}
@6uliver most mehet

2021-02-11 15:27 UTC, SiposGergo approved these changes
ok

2021-02-11 15:28 UTC, merged