!38-felhasznalok-szurese-aktivitas-szerint
flowacademyhu/iota-munkalap pull request #61
Opened 2021-02-12 12:38 UTC by danielvarsas

ListActiveUsers controller/service létrehozva
Teszt done active és inactive lekérésre

2021-02-12 14:50 UTC, borosr requested changes

2021-02-12 14:50 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/UserService.java
> +    public List<User>  getActiveUsers(@NonNull boolean active) throws ValidationException {
Legyünk konzisztensek, legyen ez is wrapper class primitív helyett. És ne legyen két space a függvény neve előtt.

2021-02-12 14:50 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/UserService.java
> +        return active ? users
Hatékonyabb, ha az adatbázisra bízod a szűrést, írj rá egy method based query-t, ahelyett, hogy stream-mel szűrnél.

2021-02-15 08:25 UTC, VicziTomi requested changes
PR által lezárandó issuet jelöljük pliz!

2021-02-15 13:27 UTC, closed without merging