Fix/#62 front end kommunikacio back enddel
flowacademyhu/iota-munkalap pull request #63
Opened 2021-02-14 12:16 UTC by Aniko-S

Beállítottam a proxy-t, a back endhez szükséges linket adtam át az eddig használt adatbázis helyett.
Munkavállaló létrehozásánál, módosításánál és a munkavállalók listájának kiírásánál átírtam a nevet vezetéknévre és keresztnévre, mert back enden így tároljuk.

2021-02-14 14:47 UTC, VicziTomi requested changes
PR elnevezést javítsd pliz, utána ok

2021-02-14 15:00 UTC, 6uliver commented on frontend/src/employees/UpdateEmployeeForm.js
> +  title, first_name, last_name, email }) {
camelCase legyen. ha az API miatt nem az, akkor az API-t alakítsátok ki úgy, hogy camelCase-t várjon a JSON-ökben. a Google style guide követendő ebben, JSON API-knál a propertyket camelCase-zel írjuk: https://google.github.io/styleguide/jsoncstyleguide.xml

2021-02-14 15:01 UTC, 6uliver commented on frontend/src/style.css
> +  height: auto;
.h-auto jobb lenne, ott lokális lenne a formázás, ezt innen nehéz látni, hogy mit formáz.

2021-02-14 16:50 UTC, Aniko-S commented on frontend/src/employees/UpdateEmployeeForm.js
> +  title, first_name, last_name, email }) {
Igen, az API így várja. @borosr kérte, hogy így legyen.

2021-02-15 08:10 UTC, borosr commented on frontend/src/employees/UpdateEmployeeForm.js
> +  title, first_name, last_name, email }) {
Oké, veszek fel rá ticketet és egységesen átírjuk camelCasere.

2021-02-15 09:31 UTC, 6uliver commented on frontend/src/Button.js
> +        :`rounded bg-success text-light my-3 mx-5`
Ez erősen duplikált így, egyszerűbb megoldás lehet, ha a className-et mindig hozzáfűzöd és a paraméterlistában kap default értéket: text, className = '', ...props

2021-02-15 09:33 UTC, 6uliver commented on frontend/src/employees/UpdateEmployee.js
>            email={userData.email}
Nem lenne jobb egyben átadni a userData-t propként és a komponensben belül szétkapni? user={userData}

2021-02-15 10:14 UTC, VicziTomi approved these changes
ok

2021-02-15 10:55 UTC, 6uliver commented on frontend/src/Button.js
> +function Button({text, className, ...props}) {
Mármint itt gondoltam default üres stringet adni, nem a használat helyén: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2021-02-15 11:42 UTC, merged