Feature/felhasznalo inaktivalas #36
flowacademyhu/iota-munkalap pull request #74
Opened 2021-02-15 10:12 UTC by nomansnick

Szia!
feltöltöttem az inaktiválást/aktiválást.
inaktiválás/aktiválás egy endpointon, id-t PathVariable-ben kapja, request paramban kapja h mire állítsuk, enumhoz hasonlítva (status enum- acitve, inactive), happy path tesztelve.

2021-02-15 10:17 UTC, VicziTomi requested changes
PR elnevezést módosítsuk kérem, aztán részemről rendben!

2021-02-15 11:18 UTC, VicziTomi approved these changes

2021-02-15 16:35 UTC, borosr requested changes

2021-02-15 16:35 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/UserController.java
> +    @PostMapping("/users/{id}")
Legyen inkább PUT

2021-02-15 16:35 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/controller/UserController.java
> +                              @RequestParam(value = "status") String status) throws ValidationException {
Legyen inkább path variable az id után és lehet a típusa Status.

2021-02-15 16:35 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/KeycloakClientService.java
> +        ourRealm.users().search(user.getEmail()).get(0).setEnabled(user.isEnabled());
Legyen egy method chaining az egész, nem kell külön változó hozzá

2021-02-15 16:35 UTC, borosr commented on backend/src/main/java/hu/flowacademy/worksheet/service/UserService.java
> +        toChange.setEnabled(status.toLowerCase().equals(Status.active.name()));
Ha enumként kapod meg a Status-t, akkor nem is kell equals, elég a hagyományos összehasonlítás.

2021-02-16 08:32 UTC, borosr commented
Old fel a conflictokat

2021-02-16 11:00 UTC, borosr approved these changes

2021-02-16 11:00 UTC, merged